XmonteroEmperorsClientBundle_root:
    pattern: /
    defaults: { _controller: XmonteroEmperorsClientBundle:Default:root }
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_game:
    pattern: /game/{gameId}
    defaults: { _controller: XmonteroEmperorsClientBundle:Default:game }
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_instructionsMenu:
    pattern: /firstgame/instructions/menu/
    defaults:
        _controller: XmonteroEmperorsClientBundle:Default:dumpPage
        template: XmonteroEmperorsClientBundle:Pages/FirstGame:instructions.html.twig
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_instructionsGame:
    pattern: /firstgame/instructions/game/
    defaults:
        _controller: XmonteroEmperorsClientBundle:Default:dumpPage
        template: XmonteroEmperorsClientBundle:Pages/FirstGame:game.html.twig
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_instructionsEmperors:
    pattern: /firstgame/instructions/emperors/
    defaults:
        _controller: XmonteroEmperorsClientBundle:Default:dumpPage
        template: XmonteroEmperorsClientBundle:Pages/FirstGame:emperors.html.twig
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_instructionsPawns:
    pattern: /firstgame/instructions/pawns/
    defaults:
        _controller: XmonteroEmperorsClientBundle:Default:dumpPage
        template: XmonteroEmperorsClientBundle:Pages/FirstGame:pawns.html.twig
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_board:
    pattern: /game/board/{turn}
    defaults: { _controller: XmonteroEmperorsClientBundle:Default:board }
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_players:
    pattern: /game/players/
    defaults: { _controller: XmonteroEmperorsClientBundle:Default:playersList }
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_privacy:
    pattern: /privacy/
    defaults:
        _controller: XmonteroEmperorsClientBundle:Default:dumpPage
        template: XmonteroEmperorsClientBundle:Pages:privacy.html.twig
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_dirty:
    pattern: /dirty/
    defaults: { _controller: XmonteroEmperorsClientBundle:Default:dirty }
    requirements: { _method: GET }
