parameters:

services:
    emperors.board.manager:
        class: Xmontero\Emperors\ModelBundle\Model\Board\BoardManager
        arguments: [ '@emperors.objectstorage.manager' ]

    emperors.piece.manager:
        class: Xmontero\Emperors\ModelBundle\Model\Pieces\PieceManager
        arguments: []

    emperors.game.manager:
        class: Xmontero\Emperors\ModelBundle\Model\Game\GameManager
        arguments: [ '@emperors.board.manager', '@emperors.piece.manager', '@emperors.objectstorage.manager' ]

    emperors.objectstorage.manager:
        class: Xmontero\Emperors\ModelBundle\Model\ObjectStorage\ObjectStorageManager
        arguments: [ '@logger', '@doctrine' ]
