parameters:

services:
    emperors.board.manager:
        class: Xmontero\Emperors\ModelBundle\Model\Game\BoardManager
        arguments: [ '@logger', '@emperors.objectstorage.manager' ]

    emperors.game.manager:
        class: Xmontero\Emperors\ModelBundle\Model\Game\GameManager
        arguments: [ '@logger', '@emperors.objectstorage.manager' ]

    emperors.objectstorage.manager:
        class: Xmontero\Emperors\ModelBundle\Model\ObjectStorage\ObjectStorageManager
        arguments: [ '@logger', '@doctrine' ]
