XmonteroEmperorsAdminBundle_dashboard:
    pattern: /
    defaults: { _controller: XmonteroEmperorsAdminBundle:Default:dashboard }
    requirements: { _method: GET }

XmonteroEmperorsAdminBundle_users:
    pattern: /users/
    defaults: { _controller: XmonteroEmperorsAdminBundle:Users:main }
    requirements: { _method: GET }

XmonteroEmperorsAdminBundle_boardEditor:
    pattern: /board/editor/
    defaults: { _controller: XmonteroEmperorsAdminBundle:BoardEditor:showEditor }
    requirements: { _method: GET }

XmonteroEmperorsClientBundle_dirty:
    pattern: /dirty/
    defaults: { _controller: XmonteroEmperorsAdminBundle:Default:dirty }
    requirements: { _method: GET }
